### ISSUE TITLE
怎么跑起来呢？

### ISSUE THREAD

**Issue by yimac** [yelloxing/clay#18]
有示例代码吗？

**Comment by yelloxing** [comment]
有，面前在针对项目打改版，你可以看看以前版本，有文档和例子。https://github.com/yelloxing/clay/tree/3e54077cdcd56ff246a106f1761217aa6fb26f9e 发自网易邮箱大师 在2018年10月31日 17:02，yimac 写道： 有示例代码吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by yelloxing** [comment]
代码clone到本地以后，直接打开doc文件夹里面的index.html即可，你会打开文档首页，里面有你需要的

**Comment by yelloxing** [comment]
目前项目在进行比较大的调整，如果想了解项目，可以查看以前版本：【地址：https://github.com/yelloxing/clay/tree/3e54077cdcd56ff246a106f1761217aa6fb26f9e 】
把代码clone到本地以后，只需要在浏览器中打开doc/index.html即可访问，其中有项目的用例和说明文档等。

**Comment by yimac** [comment]
doc 这个目录没有诶

**Comment by yelloxing** [comment]
[clay-master.zip](https://github.com/yelloxing/clay/files/2537332/clay-master.zip)
你下载这个版本，最新版本要等改造好才可以使用

**Comment by yelloxing** [comment]
新版本已经调整结束，你可以在doc查看文档api和基本说明

**Comment by chen351012** [comment]
例子滴？怎么以前的例子找不到了

**Comment by yelloxing** [comment]
除了clay核心部分和必要文档外，别的都迁移到ClayFoundation下了，例子项目是：https://github.com/ClayFoundation/examples
