### ISSUE TITLE
关于本地npm install相关问题 

### ISSUE THREAD

**Issue by paper520** [yelloxing/clay#21]
搭建本地开发环境的时候，在命令行执行：

cd clay && npm install
的时候，总是安装失败。

**Comment by paper520** [comment]
就是安装phantom.js等待了很久都没有反应，有时候直接失败。

**Comment by paper520** [comment]
那如果我就想用npm怎么办

**Comment by yelloxing** [comment]
那你可以在package.json中把
`"grunt-contrib-qunit": "^3.0.1"`
删除调再安装，这是用于命令行单元测试，你可以直接打开单元测试html进行测试，这也是可以的

**Comment by chen351012** [comment]
既然之间打开html也可以，为什么非要安装这个？

**Comment by yelloxing** [comment]
随着代码越来越多，不可能每次开发结束都一一去进行单元测试，因此提供命令行统一检测

**Comment by yelloxing** [comment]
目前已经把grunt-contrib-qunit从统一安装中移除了，你可以在需要的时候运行npm run test时安装，或者你可以选择直接在浏览器中打开对应的html
