### ISSUE TITLE
使用过程中可优化建议

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/clay#26]
1.区域管理者者可以把fill的动作放开，有时候可能想记录的是边界

**Comment by yelloxing** [comment]
2.除了arc,别的一些基本图形也可以提供一下，另外，不规则图形插值画法很有价值

**Comment by chen351012** [comment]
3.新布局（比如饼环境等），辅助方法也可以添加一些新的，比如针对树图的额外计算方法
